# Generated by Django 3.0.4 on 2020-04-02 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vislib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('chart_name', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=512, null=True)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=vislib.models.default_datetime)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=512, null=True)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=vislib.models.default_datetime)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartBoardMap',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=vislib.models.default_datetime)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vislib.Chart')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vislib.Dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='BoardOrder',
            fields=[
                ('order', models.TextField()),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=vislib.models.default_datetime)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
