# Generated by Django 3.0.4 on 2020-04-14 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vislib.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vislib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDataBase',
            fields=[
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('database', models.CharField(max_length=32)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=vislib.models.default_datetime)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDataTable',
            fields=[
                ('table', models.CharField(max_length=32)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=vislib.models.default_datetime)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vislib.SourceDataBase')),
            ],
        ),
    ]
