# Generated by Django 3.0.4 on 2020-04-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vislib', '0002_sourcedatabase_sourcedatatable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcedatabase',
            old_name='id',
            new_name='source_id',
        ),
    ]
