# Generated by Django 3.0.4 on 2020-04-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vislib', '0004_auto_20200415_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedatabase',
            name='base_alias',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcedatatable',
            name='table_alias',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
