# Generated by Django 3.0.4 on 2020-04-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vislib', '0006_sourcedatatable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='source_id',
            field=models.ForeignKey(default='ce2f9129-c4a8-40fe-934f-1385824ca23c', on_delete=django.db.models.deletion.CASCADE, to='vislib.SourceDataBase'),
            preserve_default=False,
        ),
    ]
