# Generated by Django 3.0.4 on 2020-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vislib', '0007_chart_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedatabase',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
